export default {
    AUTH: {
        USER_EXITS: "USER_EXITS",
        USERNAME_NOT_EXITS: "USERNAME_NOT_EXITS",
        INVALID_TOKEN: "INVALID_TOKEN",
        TOKEN_EXPIRED: "TOKEN_EXPIRED",
        PERMISSON_DENIED: "PERMISSON_DENIED",
        REGISTER_SUCCESS: "REGISTER_SUCCESS",
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        WRONG_PASSWORD: "WRONG_PASSWORD",
        SEND_EMAIL_SUCCESS: "SEND_EMAIL_SUCCESS",
        RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
        EMAIL_INVALID: "EMAIL_INVALID",
        RESET_PASSWORD_TOKEN_INVALID: "RESET_PASSWORD_TOKEN_INVALID",
    }
}